
--String line = "2017-01-01 23:59:28.740|192.168.112.165|\"GET / HTTP/1.1\"|200|\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0\"";

CREATE TABLE(LOG)
DATETIME [PK]
IP       [PK]
METHOD
STATUS
USER_AGENT


CREATE TABLE(THRESHOLD_LOG)

DATETIME [PK]
IP
START_DATE
THRESHOLD
DURATION
STATUS

CREATE TABLE(HTTP_STATUS)

INSERT INTO HTTP_STATUS(ID, DESC) VALUES (400,'Bad Request');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (401,'Unauthorized');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (402,'Payment Required');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (403,'Forbidden');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (404,'Not Found');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (405,'Method Not Allowed');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (406,'Not Acceptable');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (407,'Proxy Authentication Required');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (408,'Request Timeout');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (409,'Conflict');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (410,'Gone');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (411,'Length Required');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (412,'Precondition Failed');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (413,'Payload Too Large');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (414,'URI Too Long');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (415,'Unsupported Media Type');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (416,'Range Not Satisfiable');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (417,'Expectation Failed');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (421,'Misdirected Request');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (422,'Unprocessable Entity');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (423,'Locked');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (424,'Failed Dependency');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (425,'Unassigned');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (426,'Upgrade Required');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (427,'Unassigned');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (428,'Precondition Required');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (429,'Too Many Requests');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (430,'Unassigned');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (431,'Request Header Fields Too Large');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (451,'Unavailable For Legal Reasons');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (500,'Internal Server Error');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (501,'Not Implemented');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (502,'Bad Gateway');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (503,'Service Unavailable');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (504,'Gateway Timeout');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (505,'HTTP Version Not Supported');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (506,'Variant Also Negotiates');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (507,'Insufficient Storage');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (508,'Loop Detected');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (509,'Unassigned');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (510,'Not Extended');
INSERT INTO HTTP_STATUS(ID, DESC) VALUES (511,'Network Authentication Required');